version: "3"

networks:
  ZabbixNet:
    driver: bridge
    name: Zabbix
    ipam:
      driver: default
      config:
      - subnet: 172.16.2.0/24

services:
  ZabbixPostgres:
    container_name: ZabbixPostgres
    image: postgres:13.6
    networks:
      ZabbixNet:
        ipv4_address: 172.16.2.20
    ports:
      - "5432:5432"
    volumes:
      - PostgresData:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix

  ZabbixServer:
    container_name: ZabbixServer
    image: zabbix/zabbix-server-pgsql:alpine-latest
    networks:
      ZabbixNet:
        ipv4_address: 172.16.2.10
    restart: always
    ports:
      - "10051:10051"
    volumes:
      - ZabbixConfig:/etc/zabbix
      - ZabbixAlertScripts:/usr/lib/zabbix/alertscripts
      - ZabbixExternalScripts:/usr/lib/zabbix/externalscripts
      - ZabbixExport:/var/lib/zabbix/export
      - ZabbixSNMPTraps:/var/lib/zabbix/snmptraps
      - /etc/timezone:/etc/timezone
    environment:
      DB_SERVER_HOST: 172.16.2.20
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    depends_on:
      - ZabbixPostgres

  ZabbixFrontend:
    container_name: ZabbixFrontend
    image: zabbix/zabbix-web-apache-pgsql:alpine-latest
    networks:
      ZabbixNet:
        ipv4_address: 172.16.2.11
    restart: always
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - /etc/timezone:/etc/timezone
    environment:
      DB_SERVER_HOST: 172.16.2.20
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: 172.16.2.10
      PHP_TZ: Europe/Berlin
    depends_on:
      - ZabbixPostgres
      - ZabbixServer

  ZabbixSNMPTraps:
    container_name: ZabbixSNMPTraps
    image: zabbix/zabbix-snmptraps:alpine-latest
    networks:
      ZabbixNet:
        ipv4_address: 172.16.2.12
    restart: always
    ports:
      - "162:1162/udp"
    volumes:
      - ZabbixSNMPTraps:/var/lib/zabbix/snmptraps
      - ZabbixSNMPMIBs:/var/lib/zabbix/mibs
      - /etc/timezone:/etc/timezone
    depends_on:
      - ZabbixServer

  Grafana:
    container_name: Grafana
    image: grafana/grafana:8.4.3
    networks:
      ZabbixNet:
        ipv4_address: 172.16.2.13
    restart: always
    ports:
      - "3000:3000"
    environment:
       - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - GrafanaData:/var/lib/grafana
      - /etc/timezone:/etc/timezone
    depends_on:
      - ZabbixPostgres
      - ZabbixServer


volumes:
  PostgresData:
    driver: local
    name: PostgresData
  ZabbixConfig:
    driver: local
    name: ZabbixConfig
  ZabbixExport:
    driver: local
    name: ZabbixExport
  ZabbixAlertScripts:
    driver: local
    name: ZabbixAlertScripts
  ZabbixExternalScripts:
    driver: local
    name: ZabbixExternalScripts
  ZabbixSNMPTraps:
    driver: local
    name: ZabbixSNMPTraps
  ZabbixSNMPMIBs:
    driver: local
    name: ZabbixSNMPMIBs
  GrafanaData:
    driver: local
    name: GrafanaData
